// COURSE ACTION
export const FETCH_COURSE = "FETCH_COURSES"
export const FETCH_CATEGORIES = "FETCH_CATEGORIES"
export const FETCH_COURSES_BY_CATEGORIES = "FETCH_COURSES_BY_CATEGORIES"
export const ADD_COURSE_TO_CART = "ADD_COURSE_TO_CART"
export const REMOVE_COURSE_FROM_CART = "REMOVE_COURSE_TO_CART"
export const FETCH_COURSE_DETAIL = "FETCH_COURSE_DETAIL"

//CREDENTIAL ACTION
export const FETCH_CREDENTIALS = "FETCH_CREDENTIALS"
export const FETCH_FACEBOOK = "FETCH_FACEBOOK"
export const LOG_OUT = "LOG_OUT"

// USER ACTION
export const REGISTER_COURSE = "REGISTER_COURSE"
export const FETCH_INFORMATION = "FETCH_INFORMATION"
